---
- hosts: ras
  become: yes
  gather_facts: no
  tasks:
    - name: apt upgrade
      apt:
        update_cache: yes
        cache_valid_time: 3600
        force_apt_get: yes
        upgrade: true
      register: apt_result